### ISSUE TITLE
服务启动后异常终止

### ISSUE THREAD

**Issue by guangtoudun** [Hsword/SpotServe#6]
当我执行脚本  `aws_e2e.sh reparallelization 6.7B As`

报错
```
[2024-07-26 11:42:36.911325] logfiles in SpotServe-artifact/elastic-switch/log/6.7B/real/baseline_tpt1.5_cv6-0304
[2024-07-26 11:42:36.913075] gs TcpThread, listening, 1721994156.913
[2024-07-26 11:42:37.853532] gs, accepted from pc rank 9, 1721994157.854
[2024-07-26 11:42:37.861020] gs, accepted from pc rank 8, 1721994157.861
[2024-07-26 11:42:37.861646] gs, accepted from pc rank 5, 1721994157.862
[2024-07-26 11:42:37.861808] gs, accepted from pc rank 4, 1721994157.862
[2024-07-26 11:42:37.862042] gs, accepted from pc rank 7, 1721994157.862
[2024-07-26 11:42:37.862121] gs, accepted from pc rank 6, 1721994157.862
[2024-07-26 11:42:44.969868] gs, accepted from pc rank 2, 1721994164.970
[2024-07-26 11:42:45.016907] gs, accepted from pc rank 1, 1721994165.017
[2024-07-26 11:42:45.188154] gs, accepted from pc rank 3, 1721994165.188
[2024-07-26 11:42:45.230694] gs, accepted from pc rank 0, 1721994165.231
[2024-07-26 11:42:45.275082] (0.000) system initialized.
[2024-07-26 11:42:45.275225] (0.000) next-event: add at 0.000, waiting...
[2024-07-26 11:42:45.275558] (0.000) cur_nnodes: 7, next_strategy: (1, 4, 1, 4, 4, 1), requited_tpt=2.0
[2024-07-26 11:42:45.275718] (0.001) **init** set new strategy (1, 4, 1, 4, 4, 1) to shared memory
[2024-07-26 11:42:45.277036] batch_requests: False
.
.
.
[2024-07-26 11:42:46.003677] >>>>> (0.709) -- (0.709) dispatch query 0 to replica 0, n: 1, pool: 0
[2024-07-26 11:42:46.614326] >>>>> (1.320) -- (1.319) dispatch query 1 to replica 0, n: 1, pool: 1
[2024-07-26 11:42:47.302399] >>>>> (2.008) -- (2.008) dispatch query 2 to replica 0, n: 1, pool: 2
[2024-07-26 11:42:47.891319] >>>>> (2.597) -- (2.596) dispatch query 3 to replica 0, n: 1, pool: 3
[2024-07-26 11:42:48.638453] >>>>> (3.344) -- (3.344) dispatch query 4 to replica 0, n: 1, pool: 4
[2024-07-26 11:42:49.300773] >>>>> (4.006) -- (4.006) dispatch query 5 to replica 0, n: 1, pool: 5
[2024-07-26 11:42:49.991542] >>>>> (4.697) -- (4.697) dispatch query 6 to replica 0, n: 1, pool: 6
[2024-07-26 11:42:50.825222] >>>>> (5.530) -- (5.530) dispatch query 7 to replica 0, n: 1, pool: 7
[2024-07-26 11:42:55.454942] >>>>> (10.160) -- (6.221) dispatch query 8 to replica 0, n: 4, pool: 7
[2024-07-26 11:42:55.454987] >>>>> (10.160) -- (6.832) dispatch query 9 to replica 0, n: 4, pool: 8
[2024-07-26 11:42:55.455010] >>>>> (10.160) -- (7.542) dispatch query 10 to replica 0, n: 4, pool: 9
[2024-07-26 11:42:55.455029] >>>>> (10.160) -- (8.168) dispatch query 11 to replica 0, n: 4, pool: 10
[2024-07-26 11:46:15.288729] (210.014) cur_nnodes: 8, next_strategy: (2, 4, 1, 4, 4, 1), requited_tpt=2.0
[2024-07-26 11:46:15.288793] (210.014) switching from (1, 4, 1, 4, 4, 1) to (2, 4, 1, 4, 4, 1)
[2024-07-26 11:46:15.289258] (210.014) set new strategy (2, 4, 1, 4, 4, 1) to shared memory, estimate transfer cost: -0.500
[2024-07-26 11:46:15.346544] cluster strategy changed, state: 1, strategy: (2, 4, 1, 4, 4, 1), is_finished: False
[2024-07-26 11:46:15.346719] api_server close replicas 0...
[2024-07-26 11:46:15.346736] api_server send xfer_cost -0.5...
Process api_server:
Traceback (most recent call last):
  File "/usr/lib64/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib64/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ansible/SpotServe-artifact/elastic-switch/scheduler/api_server.py", line 538, in deploy_api_server
    asyncio.run(api_server.run())
  File "/usr/lib64/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/ansible/SpotServe-artifact/elastic-switch/scheduler/api_server.py", line 532, in run
    await asyncio.gather(self.watch_cluster(), self.dispatch_request())
  File "/home/ansible/SpotServe-artifact/elastic-switch/scheduler/api_server.py", line 311, in watch_cluster
    await self.send_xfer_cost(xfet_cost, replicas_to_close)
  File "/home/ansible/SpotServe-artifact/elastic-switch/scheduler/api_server.py", line 272, in send_xfer_cost
    await self.api_agent[replica_id].request_agent.async_send(struct.pack('ii', -2, -2))
  File "/home/ansible/SpotServe-artifact/elastic-switch/util/util.py", line 52, in async_send
    sent = self.conn.send(msg)
ConnectionResetError: [Errno 104] Connection reset by peer

**Comment by cblmemo** [comment]
Hi @guangtoudun , have you resolved this issue? I encountered similar error and it would be really helpful if you could share how you resolved this ; )

**Comment by guangtoudun** [comment]
> Hi @guangtoudun , have you resolved this issue? I encountered similar error and it would be really helpful if you could share how you resolved this ; )
<img width="638" alt="image" src="https://github.com/user-attachments/assets/e498eba3-c10e-44b5-b5b9-a94b1a0d5491">

这类文件的最后一列数据有问题，导致读取请求数据错误。

**Comment by cblmemo** [comment]
> > Hi @guangtoudun , have you resolved this issue? I encountered similar error and it would be really helpful if you could share how you resolved this ; )
> 
> <img alt="image" width="638" src="https://private-user-images.githubusercontent.com/100063582/374519748-e498eba3-c10e-44b5-b5b9-a94b1a0d5491.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0MTA0MjQsIm5iZiI6MTcyODQxMDEyNCwicGF0aCI6Ii8xMDAwNjM1ODIvMzc0NTE5NzQ4LWU0OThlYmEzLWMxMGUtNDRiNS1iNWI5LWE5NGIxYTBkNTQ5MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOFQxNzU1MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZGIwZjUyNzBlNDMwYzVlNzdlNGFmNmEyMTAyZjg0Y2FjNzVkYTM3ZmFkZmQyMzYxMWMyY2E0MDFiYzE4ZDEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.SjMKkfyjUgB37sa8s2xluAzD0MNQt0dEPrNfPJagWwI">
> 这类文件的最后一列数据有问题，导致读取请求数据错误。

Thanks for the prompt reply! Would you mind elaborating on what the problem is and how you modify it to get it running properly? This would be really helpful 🙌

**Comment by guangtoudun** [comment]
![image](https://github.com/user-attachments/assets/f7853ebe-4270-4187-b866-008a21bfddf9)
QUERY_FILE 一行为一条请求，QUERY_TRACE 是请求的trace，最后一列即当前请求行在QUERY_FILE的偏移。

当前逻辑是根据QUERY_TRACE读取QUERY_FILE的某一行，读取后需要将字符串转为数字，由于偏移错误导致请求读取错误，再导致字符串转数字出错，从而导致该client断开。（我记得某个log有对应的报错，好像是 param_client.log）

解决方法：重新计算QUERY_FILE每行开始的偏移，替换QUERY_TRACE的最后一列。

**Comment by guangtoudun** [comment]
![image](https://github.com/user-attachments/assets/f7853ebe-4270-4187-b866-008a21bfddf9)
QUERY_FILE 一行为一条请求，QUERY_TRACE 是请求的trace，最后一列即当前请求行在QUERY_FILE的偏移。

当前逻辑是根据QUERY_TRACE读取QUERY_FILE的某一行，读取后需要将字符串转为数字，由于偏移错误导致转换错误，从而导致该client断开。

解决方法：重新计算QUERY_FILE每行开始的偏移，替换QUERY_TRACE的最后一列。

**Comment by cblmemo** [comment]
Thanks! That really helps. I found this is also the root cause of the problem described in #8.
